services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  back:
    build: ./back
    container_name: schooltool-back
    volumes:
      - ./back:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      TAB_ROLES: '[ {"id": 1, "name": "student", "access": "Student_Access"}, {"id": 2, "name": "hors-parcours"}, {"id": 3, "name": "alumni"}, {"id": 4, "name": "admin"}, {"id": 5, "name": "crm", "access": "CRM_Access"}, {"id": 6, "name": "corrector", "access": "Corrector_Access"}, {"id": 7, "name": "teacher", "access": "Teacher_Access"}, {"id": 8, "name": "peda", "access": "Peda_Access"}, {"id": 9, "name": "re", "access": "Re_Access"}]'
      DB_HOST: db
      DB_USER: root
      DB_PWD: root
      DB_NAME: schooltool_api
      LPTF_JWT_KEY: toto
      GOOGLE_CLIENT_ID: "108943179163543703723"
      GOOGLE_CLIENT_EMAIL: atlas-793@atelier-385117.iam.gserviceaccount.com
      GOOGLE_PRIVATE_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCq1DvgxEWctrXo
        ok8A46iVO1oQKfWSsWISMB7Au12QM08VFrlOiROFJi7iP39+U9hVg3vvoLAH29qj
        xkPS9Z6r+yvz15ELlZyTjz623FaEAcustjKgdwrgpd7y3IRI8PbV4ljLr2yZTl89
        0mXwnMcspRzvDAc3ffXG4JeXoYDrG7XLhi4+me2G0ZMLNsMi0j/xW3uO4r0/ioYn
        acXShmtKXKo+ZsaRAyDBVGYYEvLimWHOd9dUdniGjrLW3WeX1lXIeW6JrZu07a/g
        n5ZMy4FxIJp8MPjU+ZLtP6S5BBB1QKBDbquABW7UTJWH9EByWc6EHrf6+WOw0OPJ
        vr2kzNu7AgMBAAECggEAH/9T3eR1k4aHqTTprmV2GMm+s2Ngm6L9FyILSJdvzYhG
        ylDw0byMOvbtdjRlmZBz54SSzM4g2r/8Aowq/RNDrrwDvg9FHFHgO6Vrnk3EKMK7
        VzTjY7oYf/6htYTHhHAaE/LrJe/MXCTZYxeLP5fmGL8unbn3ihXeWOuNiXnXT3IZ
        I/FCUnmsLaILpPsd7hU6HPvKdlFEoN0ihjiUOdekgIrePzN8yoVhrIAdjN8rn0Tm
        eeAOPBrSvkD/72UVfAkW4Bn00jT6tvzqRK9Jr0KMOCgb6lnhirWjBKquYmQU2yAL
        IZjz4kp5Sz7MPCzfs4v2Je4PCmulz03xLa0jqDwzWQKBgQDkcweABePaF5ES5nhq
        LiGP2xK3vOqlEDiXSj2oUGQUUWpafhP7UJal2PNOw0faMNas9ZIV36m406azaziN
        U1pqq5QO58mK0qo6cvoSBdOa93KfaOoSHQw8tmcWfVuwqCidfzZYtpfx8/r1n5D6
        oB29KbwCIUBJlqdbLGaCdALK6QKBgQC/bkeOdIWuAzXWjcWjVFNsFh6RHtrjiOfb
        1lHHmYPL2RAInW3KUs2t2PDcgDU5sq1+A9DDZx41uTsECBLSNxVeNy/IwbrBNbB9
        yfVBvWLVGWXSkPC2LXhT3J1T3r2xXpEY7pLnzu+uVAdEphlt6m7ViLhW+SBGaJ9K
        CcAZy23DAwKBgQCJOrAer2sX72AuQlPDNMLkb2znAozRatUTzH0NRn1X1zBT+7h1
        FwvnxFMj1RqsbvoGG94NVbXWWQ2iaZ4nBxMhUMA30/S1d6baRYcCnI1oYYxxRcyV
        5O0c61UxpUwW6my7b1duIwFTToRKV/f3FYfHwfI2NVMw4VbW5e0OIDItQQKBgQCo
        ftQDIrMLoI3B5RXiFnY7PBj5mVQHVNjoWnOvIYOtaMjBHHinzkx1ye7v1vWCbLBi
        q88UP26K0RiOCuEuIQfw3thzd3n/WFeZ0KrMi3szoOBMAAGwCMPR5OyiBvum5FsI
        u+2Ylj/HjPS8ywq1AdU+pNHE1BFBiBM04vIwgiuBqwKBgAWoTUBmdo0vm1SlZJu/
        E0SV53+Ubir0zWLwL/4F8Yi69Rf2LbQ2HdtWgbIdXYfDXrtWzX6fx5j0aX19Jv6u
        sx5Xl3af+j43U2uRDvG2Q5043pgBEu9Zn01BYd3KAUKotcID2+SdUF5XfDlFdQzX
        Z6zDnlLza1WZWEBLc7A4sHZg
        -----END PRIVATE KEY-----
      GOOGLE_DRIVE_ABSENCE_FOLDER: "1TlMbaF8QQJ8eY7OQQFr0v1-LooKgcNzz"
      IS_DEV: true

  auth:
    build: ./auth
    container_name: schooltool-auth
    volumes:
      - ./auth:/var/www/html
    ports:
      - '8001:80'
    depends_on:
      - db
    environment:
      TAB_ROLES: '[ {"id": 1, "name": "student", "access": "Student_Access"}, {"id": 2, "name": "hors-parcours"}, {"id": 3, "name": "alumni"}, {"id": 4, "name": "admin"}, {"id": 5, "name": "crm", "access": "CRM_Access"}, {"id": 6, "name": "corrector", "access": "Corrector_Access"}, {"id": 7, "name": "teacher", "access": "Teacher_Access"}, {"id": 8, "name": "peda", "access": "Peda_Access"}, {"id": 9, "name": "re", "access": "Re_Access"}]'
      DB_HOST: db
      DB_USER: root
      DB_PWD: root
      DB_NAME: schooltool_auth
      LPTF_JWT_KEY: toto
      GOOGLE_CLIENT_ID: '604347883543-cu73up3fqo5r9gn18tqpkf3tu9ud41s4.apps.googleusercontent.com'
      IS_DEV: true
      OAUTH_URL: 'http://localhost:8001/oauth'

  front:
    build: ./front
    container_name: schooltool-front
    tty: true
    stdin_open: true
    volumes:
      - ./front:/app
    ports:
      - '8082:8081'
      - '19000:19000' # Metro Bundler
      - '19001:19001' # WebSocket (live/hot reload)
      - '19002:19002' # React Native Debugger
    depends_on:
      - back
      - auth
    environment:
      API_URL: 'http://localhost:8000'
      AUTH_URL: 'http://localhost:8001'

volumes:
  db_data:
